SELECT 
    CASE 
        WHEN AU.CAPITAL_AS_OF_DATE = '00000000' THEN NULL
        WHEN LENGTH(AU.CAPITAL_AS_OF_DATE) = 8 
             AND REGEXP_LIKE(AU.CAPITAL_AS_OF_DATE, '^[0-9]{8}$') 
             AND TO_DATE(AU.CAPITAL_AS_OF_DATE, 'YYYYMMDD') IS NOT NULL 
        THEN TO_CHAR(TO_DATE(AU.CAPITAL_AS_OF_DATE, 'YYYYMMDD'), 'DD-Mon-YYYY')
        ELSE NULL
    END AS formatted_date
FROM YourTable;
